"""Parameter catalog — the single source of Chinese explanations for the Web UI.

Adding a tunable field means adding a :class:`Param` here. The frontend renders
this list; ``docs/PARAMS.zh.md`` is generated from the same data.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Literal

from webui.sandbox import schema as sandbox_schema

Kind = Literal["cli", "hydra", "preset"]
PType = Literal["int", "float", "bool", "str", "select", "float_pair", "int_list"]


@dataclass
class Param:
    id: str
    group: str
    kind: Kind
    path: str
    ptype: PType
    default: Any
    label: str
    summary: str
    bigger: str
    smaller: str
    novice: str
    min: float | None = None
    max: float | None = None
    step: float | None = None
    options: list[str] = field(default_factory=list)
    tasks: list[str] = field(default_factory=list)
    advanced: bool = False

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Tasks shown in the UI
# ---------------------------------------------------------------------------

TASKS: list[dict[str, str]] = [
    {
        "id": "PAN-CoinHold-Apex-v0",
        "play_id": "PAN-CoinHold-Apex-Play-v0",
        "label": "Stage A · 指背托币 (Hold)",
        "summary": "让硬币稳定坐在食指/中指指背上，先别掉。新手从这里开始。",
    },
    {
        "id": "PAN-CoinTransfer-Apex-v0",
        "play_id": "PAN-CoinTransfer-Apex-Play-v0",
        "label": "Stage B · 指背传递 (Transfer)",
        "summary": "在 Hold 基础上把硬币从食指-中指滚到中指-无名指。",
    },
    {
        "id": "PAN-BaodingRotate-Apex-Left-v0",
        "play_id": "PAN-BaodingRotate-Apex-Left-Play-v0",
        "label": "保健球对转 · 左手 (Baoding)",
        "summary": "掌心朝上托两颗 30 mm 木球互转。左手＝实机那只，训完可直接部署。",
    },
    {
        "id": "PAN-BaodingRotate-Apex-v0",
        "play_id": "PAN-BaodingRotate-Apex-Play-v0",
        "label": "保健球对转 · 右手",
        "summary": "同上但用右手 USD。实机是左手，右手版只用于对照。",
    },
    {
        "id": "PAN-CoinHold-Apex-Vision-v0",
        "play_id": "PAN-CoinHold-Apex-Vision-Play-v0",
        "label": "Hold + 三视角相机",
        "summary": "同一 Hold 任务，加腕/俯/侧三路相机。12 GB 显存请把并行环境降到 128。",
    },
    {
        "id": "PAN-CoinHold-Apex-Left-v0",
        "play_id": "PAN-CoinHold-Apex-Left-v0",
        "label": "左手 Hold（资产自检）",
        "summary": "换左手 USD。不是主策略，用来确认镜像资产没问题。",
    },
]

OBJECT_PRESETS = [
    {"id": "pan_coin_32mm", "label": "PΛN 硬币 32×4 mm", "kind": "coin"},
    {"id": "baoding_wood_30mm", "label": "木球 30 mm (实物)", "kind": "ball"},
    {"id": "baoding_38mm", "label": "保健球 38 mm", "kind": "ball"},
    {"id": "baoding_45mm", "label": "保健球 45 mm", "kind": "ball"},
    {"id": "baoding_50mm", "label": "保健球 50 mm", "kind": "ball"},
    {"id": "cube_60mm", "label": "立方体 60 mm", "kind": "cube"},
    {"id": "rod_80mm", "label": "短棒 80 mm", "kind": "rod"},
    {"id": "egg_45mm", "label": "蛋形 (胶囊)", "kind": "egg"},
]

HAND_POSES = [
    {"id": "palm_down_knuckle", "label": "掌心朝下 · 指背沟（滚币）"},
    {"id": "palm_up_cradle", "label": "掌心朝上 · 托举（球类）"},
]

PHYSICS_BACKENDS = [
    {"id": "physx", "label": "PhysX（默认，当前主训练引擎）"},
    {"id": "newton_mjwarp", "label": "Newton / MuJoCo-Warp（跨引擎验证）"},
]

CAMERA_LAYOUTS = [
    {"id": "none", "label": "无相机（纯状态观测）"},
    {"id": "wrist_only", "label": "仅腕部"},
    {"id": "overhead_only", "label": "仅俯视"},
    {"id": "tri_view", "label": "三视角（腕 + 俯 + 侧）"},
]


def _p(**kwargs) -> Param:
    return Param(**kwargs)


PARAMS: list[Param] = [
    # ----- scale / duration -------------------------------------------------
    _p(
        id="num_envs",
        group="规模与时长",
        kind="cli",
        path="--num_envs",
        ptype="int",
        default=512,
        min=16,
        max=2048,
        step=16,
        label="并行环境数",
        summary="同时仿真多少只手。数据收集速度几乎随它线性涨，显存也随它线性涨。",
        bigger="每秒看到更多状态，训练更快；12 GB 笔记本超过 512 很容易爆显存，开相机时更要降。",
        smaller="更省显存、更稳；太小（<128）梯度噪声大，曲线会抖。",
        novice="无相机从 512 起步；三视角相机用 128。不要一上来就 2048。",
    ),
    _p(
        id="max_iterations",
        group="规模与时长",
        kind="cli",
        path="--max_iterations",
        ptype="int",
        default=1500,
        min=10,
        max=20000,
        step=50,
        label="训练迭代次数",
        summary="PPO 更新多少轮。一轮 = 所有环境各走 num_steps_per_env 步，再做若干次梯度更新。",
        bigger="训得更久，有机会继续涨成功率；过久可能过拟合仿真。",
        smaller="更快看到结果；Hold 至少先跑到成功率开始抬头再决定停不停。",
        novice="Hold 默认 1500；Transfer / 保健球 2000。先用 50 轮冒烟确认能跑通。",
    ),
    _p(
        id="num_steps_per_env",
        group="规模与时长",
        kind="hydra",
        path="agent.num_steps_per_env",
        ptype="int",
        default=24,
        min=8,
        max=128,
        step=8,
        label="每环境每轮步数",
        summary="每次 PPO 更新前，每个环境走多少策略步。总样本 = num_envs × 这个数。",
        bigger="一次更新看到更长轨迹，优势估计更稳；显存和等待时间增加。",
        smaller="更新更勤、反应更快；优势估计更短视。",
        novice="保持 24。改它时必须保证 num_envs × 步数 能被「小批次数」整除。",
    ),
    _p(
        id="episode_length_s",
        group="规模与时长",
        kind="hydra",
        path="env.episode_length_s",
        ptype="float",
        default=3.0,
        min=1.0,
        max=20.0,
        step=0.5,
        label="一局时长（秒）",
        summary="到点就重置。策略步数 ≈ 秒数 / (sim.dt × decimation)。Hold 默认 3 s ≈ 180 步。",
        bigger="给传递/互转更多时间；折扣因子 γ 的有效视野也要配得上，否则远处奖励看不见。",
        smaller="更快重置、更密集的「掉了/成功」信号；太短会截断还没做完的动作。",
        novice="Hold 3 s，Transfer 5 s，保健球 8 s。不要低于 2 s。",
    ),
    _p(
        id="decimation",
        group="规模与时长",
        kind="hydra",
        path="env.decimation",
        ptype="int",
        default=4,
        min=1,
        max=16,
        step=1,
        label="控制抽稀",
        summary="物理步与策略步的比。dt=1/240、decimation=4 → 策略 60 Hz，和真机接近。",
        bigger="策略更慢、更省算；动作更「钝」，细滚动会变难。",
        smaller="策略更快、更灵敏；和真机 60 Hz 差得更远，sim2real 更痛。",
        novice="保持 4。这是按真机控制频率选的。",
        advanced=True,
    ),
    _p(
        id="sim_dt",
        group="规模与时长",
        kind="hydra",
        path="env.sim.dt",
        ptype="float",
        default=1.0 / 240.0,
        min=1.0 / 500.0,
        max=1.0 / 60.0,
        step=0.0005,
        label="物理步长 dt（秒）",
        summary="PhysX/Newton 每步推进多少秒。越小接触越稳，算得越慢。",
        bigger="算得快，接触容易穿透或把硬币弹飞。",
        smaller="接触更稳，训练变慢。",
        novice="保持 1/240。硬币这种小物体不要用 1/60。",
        advanced=True,
    ),
    _p(
        id="seed",
        group="规模与时长",
        kind="cli",
        path="--seed",
        ptype="int",
        default=42,
        min=-1,
        max=10000,
        step=1,
        label="随机种子",
        summary="复现实验用。-1 表示每次随机抽一个。",
        bigger="只是换一条随机轨迹，没有「更好」的方向。",
        smaller="同上。",
        novice="对比两次改参时固定同一个种子；扫参时再换。",
    ),
    # ----- PPO --------------------------------------------------------------
    _p(
        id="learning_rate",
        group="PPO",
        kind="hydra",
        path="agent.algorithm.learning_rate",
        ptype="float",
        default=0.001,
        min=1e-5,
        max=0.01,
        step=0.0001,
        label="学习率",
        summary="每次梯度更新迈多大步。本仓库默认开自适应调度，实际学习率会按 KL 自动缩放。",
        bigger="学得猛，容易把已经会的动作冲掉，KL 会爆。",
        smaller="学得稳、慢。曲线长期不动可以略微加大。",
        novice="保持 0.001 + adaptive。不要先动这个。",
    ),
    _p(
        id="schedule",
        group="PPO",
        kind="hydra",
        path="agent.algorithm.schedule",
        ptype="select",
        default="adaptive",
        options=["adaptive", "linear", "fixed"],
        label="学习率调度",
        summary="adaptive：KL 太大就自动降低学习率；linear：线性衰减；fixed：恒定。",
        bigger="fixed 最激进，容易训崩。",
        smaller="adaptive 最省心。",
        novice="保持 adaptive。",
    ),
    _p(
        id="gamma",
        group="PPO",
        kind="hydra",
        path="agent.algorithm.gamma",
        ptype="float",
        default=0.998,
        min=0.9,
        max=0.9999,
        step=0.001,
        label="折扣因子 γ",
        summary="未来奖励打几折。有效视野大约 1/(1-γ) 步。0.998 → 约 500 步，比 Hold 的 180 步还长。",
        bigger="更有耐心，会为很久之后的成功去探索；优势估计方差也更大。",
        smaller="更短视，适合稠密逐步奖励；可能学不会「先稳住再滚」。",
        novice="Hold 可试 0.99（视野≈100 步，配 180 步一局更匹配）；Transfer 保持 0.998。",
    ),
    _p(
        id="lam",
        group="PPO",
        kind="hydra",
        path="agent.algorithm.lam",
        ptype="float",
        default=0.95,
        min=0.8,
        max=1.0,
        step=0.01,
        label="GAE λ",
        summary="优势估计在「偏差」和「方差」之间的折中。1=蒙特卡洛，0=单步 TD。",
        bigger="更接近真实回报，曲线更噪。",
        smaller="更平滑、更短视。",
        novice="保持 0.95。",
        advanced=True,
    ),
    _p(
        id="clip_param",
        group="PPO",
        kind="hydra",
        path="agent.algorithm.clip_param",
        ptype="float",
        default=0.2,
        min=0.05,
        max=0.5,
        step=0.05,
        label="PPO 裁剪 ε",
        summary="一次更新最多让策略概率比改多少。防止一步走太远。",
        bigger="更新更大胆，容易把策略冲坏。",
        smaller="更新更保守，学得慢。",
        novice="保持 0.2。",
        advanced=True,
    ),
    _p(
        id="entropy_coef",
        group="PPO",
        kind="hydra",
        path="agent.algorithm.entropy_coef",
        ptype="float",
        default=0.002,
        min=0.0,
        max=0.05,
        step=0.001,
        label="熵系数",
        summary="鼓励策略保持随机、继续探索。掉到接近 0 表示探索死了。",
        bigger="动作更乱，早期有用；太大会永远不收敛。",
        smaller="更快「敢做决定」；太小容易过早锁死到一个坏动作。",
        novice="策略变得很机械、成功率卡住时略加到 0.005；动作一直发抖就略减。",
    ),
    _p(
        id="desired_kl",
        group="PPO",
        kind="hydra",
        path="agent.algorithm.desired_kl",
        ptype="float",
        default=0.01,
        min=0.001,
        max=0.05,
        step=0.001,
        label="目标 KL",
        summary="自适应学习率要盯住的策略变化量。实际 KL 长期超过它的两倍，说明步子太大。",
        bigger="允许策略跳得更远，学得快但不稳。",
        smaller="每次只挪一点点。",
        novice="保持 0.01。看曲线里的 KL，不要先改这个。",
        advanced=True,
    ),
    _p(
        id="num_learning_epochs",
        group="PPO",
        kind="hydra",
        path="agent.algorithm.num_learning_epochs",
        ptype="int",
        default=5,
        min=1,
        max=20,
        step=1,
        label="每轮回扫次数",
        summary="同一批轨迹反复拿来做几次梯度更新。",
        bigger="把这批数据榨得更干；太多次会过拟合这一批。",
        smaller="更新更保守。",
        novice="保持 5。",
        advanced=True,
    ),
    _p(
        id="num_mini_batches",
        group="PPO",
        kind="hydra",
        path="agent.algorithm.num_mini_batches",
        ptype="int",
        default=4,
        min=1,
        max=32,
        step=1,
        label="小批次数",
        summary="一批轨迹切成几份再回传。必须整除 num_envs × num_steps_per_env。",
        bigger="每步梯度用更少样本，更噪。",
        smaller="每步梯度更稳，显存峰值更高。",
        novice="保持 4。改并行环境数后跑一次「参数体检」。",
    ),
    _p(
        id="max_grad_norm",
        group="PPO",
        kind="hydra",
        path="agent.algorithm.max_grad_norm",
        ptype="float",
        default=1.0,
        min=0.1,
        max=10.0,
        step=0.1,
        label="梯度裁剪",
        summary="把梯度向量的长度上限卡住，防止一次异常样本把网络打飞。",
        bigger="几乎不裁，数值更易炸。",
        smaller="更新更钝。",
        novice="保持 1.0。",
        advanced=True,
    ),
    # ----- network ----------------------------------------------------------
    _p(
        id="hidden_dims",
        group="网络",
        kind="hydra",
        path="agent.actor.hidden_dims",
        ptype="int_list",
        default=[512, 256, 128],
        label="Actor 隐层宽度",
        summary="三层 MLP。输入是拼接后的状态向量（关节、物体、指尖…），输出每个关节一个高斯均值。",
        bigger="更能拟合复杂手法，更容易过拟合、更吃显存。",
        smaller="学得慢、表达力不够。",
        novice="保持 512,256,128。不要为了「更强」先加层。",
        advanced=True,
    ),
    _p(
        id="activation",
        group="网络",
        kind="hydra",
        path="agent.actor.activation",
        ptype="select",
        default="elu",
        options=["elu", "relu", "tanh", "silu"],
        label="激活函数",
        summary="每层非线性。ELU 是腿/手强化学习里的常见默认。",
        bigger="没有单调「更大」——换激活等于换网络性格。",
        smaller="同上。",
        novice="保持 elu。",
        advanced=True,
    ),
    _p(
        id="init_std",
        group="网络",
        kind="hydra",
        path="agent.actor.distribution_cfg.init_std",
        ptype="float",
        default=1.0,
        min=0.1,
        max=2.0,
        step=0.1,
        label="初始动作标准差",
        summary="策略一开始有多「敢乱试」。探索主要靠它和熵系数。",
        bigger="开局动作更乱，早期覆盖面大。",
        smaller="开局就比较保守，可能根本摸不到硬币。",
        novice="保持 1.0。",
        advanced=True,
    ),
    _p(
        id="obs_normalization",
        group="网络",
        kind="hydra",
        path="agent.actor.obs_normalization",
        ptype="bool",
        default=True,
        label="观测归一化",
        summary="在线估计观测均值/方差并标准化。关节和米、弧度混在一起时几乎必须开。",
        bigger="（布尔）打开后训练更稳。",
        smaller="关掉后不同量纲会互相淹没。",
        novice="保持打开。",
        advanced=True,
    ),
    # ----- rewards: hold ----------------------------------------------------
    _p(
        id="rew_coin_knuckle_distance",
        group="奖励 · Hold / 共用",
        kind="hydra",
        path="env.rewards.coin_knuckle_distance.weight",
        ptype="float",
        default=-8.0,
        min=-40.0,
        max=0.0,
        step=0.5,
        label="硬币-指节距离",
        summary="硬币中心离两指指背座位的 L2。坐稳时接近 0。负权重 = 离得越远扣越多。",
        bigger="（更负）死死按在座位上，可能不敢滚。",
        smaller="（接近 0）这项几乎没声音，容易飘走。",
        novice="Hold 保持 -8。Transfer 这项会被「桥距离」替换。",
        tasks=["PAN-CoinHold-Apex-v0", "PAN-CoinHold-Apex-Vision-v0", "PAN-CoinHold-Apex-Left-v0"],
    ),
    _p(
        id="rew_coin_seat_offset",
        group="奖励 · Hold / 共用",
        kind="hydra",
        path="env.rewards.coin_seat_offset.weight",
        ptype="float",
        default=-4.0,
        min=-20.0,
        max=0.0,
        step=0.5,
        label="离座高度",
        summary="硬币相对指背平面的 |高度|。弹起或掉到沟里都会被罚。",
        bigger="（更负）更不允许跳；可能把「翻滚」也罚掉。",
        smaller="允许更颠。",
        novice="保持 -4。",
        tasks=["PAN-CoinHold-Apex-v0", "PAN-CoinHold-Apex-Vision-v0", "PAN-CoinHold-Apex-Left-v0"],
    ),
    _p(
        id="rew_desired_contact",
        group="奖励 · Hold / 共用",
        kind="hydra",
        path="env.rewards.desired_contact.weight",
        ptype="float",
        default=2.0,
        min=0.0,
        max=20.0,
        step=0.5,
        label="期望接触",
        summary="有几根目标手指的指节在阈值内。接触传感器在实例化 USD 上挂不上，所以用距离代理。",
        bigger="更想「贴住」；Transfer 会把目标手指改成三根。",
        smaller="不在乎贴没贴。",
        novice="保持 2。",
    ),
    _p(
        id="rew_joint_vel_l2",
        group="奖励 · Hold / 共用",
        kind="hydra",
        path="env.rewards.joint_vel_l2.weight",
        ptype="float",
        default=-2.5e-5,
        min=-1e-2,
        max=0.0,
        step=1e-5,
        label="关节速度惩罚",
        summary="让手指别狂抖。量级很小，正常情况下几乎只是微调。",
        bigger="（更负）手会变僵。",
        smaller="几乎没作用。",
        novice="保持默认。若和 success=50 比会觉得差 6 个量级——这是故意的。",
        advanced=True,
    ),
    _p(
        id="rew_action_l2",
        group="奖励 · Hold / 共用",
        kind="hydra",
        path="env.rewards.action_l2.weight",
        ptype="float",
        default=-0.0001,
        min=-0.05,
        max=0.0,
        step=0.0001,
        label="动作幅度惩罚",
        summary="惩罚远离 0 的动作，鼓励待在默认指背姿态附近。",
        bigger="（更负）手更懒，可能不够用力去挡硬币。",
        smaller="允许更大动作。",
        novice="保持 -0.0001。",
        advanced=True,
    ),
    _p(
        id="rew_action_rate_l2",
        group="奖励 · Hold / 共用",
        kind="hydra",
        path="env.rewards.action_rate_l2.weight",
        ptype="float",
        default=-0.01,
        min=-0.2,
        max=0.0,
        step=0.005,
        label="动作变化率惩罚",
        summary="惩罚相邻两步动作差，抑制高频抖动（对真机齿轮友好）。",
        bigger="（更负）动作更黏、更慢。",
        smaller="允许更干脆的弹指。",
        novice="手指抖得像帕金森就略加；滚不动就略减。",
    ),
    _p(
        id="rew_drop",
        group="奖励 · Hold / 共用",
        kind="hydra",
        path="env.rewards.drop.weight",
        ptype="float",
        default=-10.0,
        min=-80.0,
        max=0.0,
        step=1.0,
        label="掉落惩罚",
        summary="硬币离开指背的那一步给一次负奖。和终止条件共用同一判定。",
        bigger="（更负）策略会极度怕掉，可能学会「僵住不动」。",
        smaller="不怕掉，乱甩。",
        novice="保持 -10。若策略完全不敢动，减到 -5 看看。",
    ),
    _p(
        id="rew_hold_ok",
        group="奖励 · Hold / 共用",
        kind="hydra",
        path="env.rewards.hold_ok.weight",
        ptype="float",
        default=1.0,
        min=0.0,
        max=20.0,
        step=0.5,
        label="坐稳奖励",
        summary="每一步只要硬币还在座位上就 +1。和成功终止用同一套判定。",
        bigger="更想「待着」；Transfer 必须把它改成 0，否则策略拒绝滚动。",
        smaller="坐稳信号变弱。",
        novice="Hold 保持 1；切到 Transfer 界面会看到默认变 0。",
    ),
    _p(
        id="rew_finger_crossing",
        group="奖励 · Hold / 共用",
        kind="hydra",
        path="env.rewards.finger_crossing.weight",
        ptype="float",
        default=-20.0,
        min=-80.0,
        max=0.0,
        step=1.0,
        label="交叉穿模惩罚",
        summary="自碰撞是关的（URDF 触觉壳静止就重叠），所以用相邻手指横向间隙当守卫。",
        bigger="（更负）更不允许并指。",
        smaller="穿模可能再次出现。",
        novice="保持 -20。日志里如果这项长期是 0，说明守卫没被踩到，是好事。",
    ),
    _p(
        id="rew_user_term",
        group="奖励 · Hold / 共用",
        kind="hydra",
        path="env.rewards.user_term.weight",
        ptype="float",
        default=0.0,
        min=-50.0,
        max=50.0,
        step=0.5,
        label="用户自定义奖励权重",
        summary="调用 user_rewards.py 里的 user_reward。自然语言生成的函数默认挂在这里，权重 0 等于关掉。",
        bigger="让大模型写的项真正参与训练。先用 Reward 探针看量级再设。",
        smaller="0 表示这项不生效。",
        novice="生成并审阅通过后，从 0.5 或 1.0 试起，不要一上来就 50。",
    ),
    # ----- rewards: transfer ------------------------------------------------
    _p(
        id="rew_progress",
        group="奖励 · Transfer",
        kind="hydra",
        path="env.rewards.progress.weight",
        ptype="float",
        default=8.0,
        min=0.0,
        max=40.0,
        step=0.5,
        label="沿指前进",
        summary="硬币在食指→小指方向上的相位增加 + 靠近中指-无名指座位的稠密拉力。",
        bigger="更想往小指方向走；太大可能「甩过去」而不是滚。",
        smaller="传递动力不足，会停在食指。",
        novice="这是 Transfer 的主驱动力，保持 8 左右。",
        tasks=["PAN-CoinTransfer-Apex-v0"],
    ),
    _p(
        id="rew_roll_rotation",
        group="奖励 · Transfer",
        kind="hydra",
        path="env.rewards.roll_rotation.weight",
        ptype="float",
        default=0.5,
        min=0.0,
        max=10.0,
        step=0.1,
        label="向前翻滚",
        summary="绕手指轴线的正向角速度，且必须同时在相位上前进。防止原地空转刷分。",
        bigger="更像「滚」而不是「滑」；过大会回去刷原地旋转。",
        smaller="不在乎滚不滚。",
        novice="保持 0.5。以前 不封顶 时策略会刷空转。",
        tasks=["PAN-CoinTransfer-Apex-v0"],
    ),
    _p(
        id="rew_slip",
        group="奖励 · Transfer",
        kind="hydra",
        path="env.rewards.slip.weight",
        ptype="float",
        default=-2.0,
        min=-20.0,
        max=0.0,
        step=0.5,
        label="滑动惩罚",
        summary="|平移 − 半径×转角|。平移了却没滚，就是在滑。",
        bigger="（更负）更强制纯滚动。",
        smaller="允许推移。",
        novice="保持 -2。",
        tasks=["PAN-CoinTransfer-Apex-v0"],
    ),
    _p(
        id="rew_success",
        group="奖励 · Transfer",
        kind="hydra",
        path="env.rewards.success.weight",
        ptype="float",
        default=50.0,
        min=0.0,
        max=200.0,
        step=5.0,
        label="传递成功奖励",
        summary="硬币到达中指-无名指座位、累积足够前滚、并保持若干帧，给一次大奖励。",
        bigger="更愿意为成功冒险；和逐步奖励比太大会变成「只赌最后一下」。",
        smaller="成功信号被逐步项淹没。",
        novice="保持 50。稀疏大奖必须明显大于一步的 progress。",
        tasks=["PAN-CoinTransfer-Apex-v0"],
    ),
    # ----- rewards: baoding -------------------------------------------------
    _p(
        id="rew_baoding_spin",
        group="奖励 · 保健球",
        kind="hydra",
        path="env.rewards.spin.weight",
        ptype="float",
        default=8.0,
        min=0.0,
        max=30.0,
        step=0.5,
        label="互转角速度",
        summary="两球连线绕掌心法向的角增量。正向转给正奖。",
        bigger="更想转起来；太大可能把球甩出掌心。",
        smaller="转得慢或不转。",
        novice="保健球任务的主奖励，从 6 起步。",
        tasks=["PAN-BaodingRotate-Apex-Left-v0", "PAN-BaodingRotate-Apex-v0"],
    ),
    _p(
        id="rew_baoding_gap",
        group="奖励 · 保健球",
        kind="hydra",
        path="env.rewards.ball_gap.weight",
        ptype="float",
        default=-4.0,
        min=-20.0,
        max=0.0,
        step=0.5,
        label="球间距",
        summary="两球中心距偏离「两半径 + 间隙」的程度。贴太紧或飞太开都罚。",
        bigger="（更负）间距更死板。",
        smaller="允许更分开。",
        novice="保持 -4。",
        tasks=["PAN-BaodingRotate-Apex-Left-v0", "PAN-BaodingRotate-Apex-v0"],
    ),
    _p(
        id="rew_baoding_center",
        group="奖励 · 保健球",
        kind="hydra",
        path="env.rewards.pair_centering.weight",
        ptype="float",
        default=-3.0,
        min=-20.0,
        max=0.0,
        step=0.5,
        label="对中掌心",
        summary="两球中点离掌心的水平距离。防止整对球滑到指尖或虎口外。",
        bigger="（更负）更想待在掌心。",
        smaller="允许往手指走。",
        novice="保持 -3。",
        tasks=["PAN-BaodingRotate-Apex-Left-v0", "PAN-BaodingRotate-Apex-v0"],
    ),
    _p(
        id="rew_baoding_drop",
        group="奖励 · 保健球",
        kind="hydra",
        path="env.rewards.drop.weight",
        ptype="float",
        default=-12.0,
        min=-80.0,
        max=0.0,
        step=1.0,
        label="掉球惩罚",
        summary="任一球落到掌面以下过多，给一次负奖。",
        bigger="（更负）更不敢转。",
        smaller="不怕掉。",
        novice="保持 -12。",
        tasks=["PAN-BaodingRotate-Apex-Left-v0", "PAN-BaodingRotate-Apex-v0"],
    ),
    # ----- domain rand ------------------------------------------------------
    _p(
        id="dr_object_mass",
        group="域随机化",
        kind="hydra",
        path="env.events.object_scale_mass.params.mass_distribution_params",
        ptype="float_pair",
        default=[0.85, 1.15],
        label="物体质量缩放",
        summary="每个环境把物体质量乘上这个区间里的随机数。用来抵抗真机硬币/球重量不准。",
        bigger="区间越宽越鲁棒，越难学。",
        smaller="更像「只练这一个球」。",
        novice="Hold 用 0.85–1.15；Transfer 已经加宽到 0.4–1.6。",
    ),
    _p(
        id="dr_object_mu_s",
        group="域随机化",
        kind="hydra",
        path="env.events.object_physics_material.params.static_friction_range",
        ptype="float_pair",
        default=[0.55, 0.90],
        label="物体静摩擦",
        summary="硬币/球表面的静摩擦系数采样区间。",
        bigger="更滑到更黏都见过。",
        smaller="摩擦更单一。",
        novice="先保持。真机打滑再加宽下限。",
    ),
    _p(
        id="dr_object_mu_d",
        group="域随机化",
        kind="hydra",
        path="env.events.object_physics_material.params.dynamic_friction_range",
        ptype="float_pair",
        default=[0.50, 0.85],
        label="物体动摩擦",
        summary="滑动起来之后的摩擦。",
        bigger="覆盖更广的表面。",
        smaller="更单一。",
        novice="保持默认。",
        advanced=True,
    ),
    _p(
        id="dr_robot_stiff",
        group="域随机化",
        kind="hydra",
        path="env.events.robot_joint_stiffness_and_damping.params.stiffness_distribution_params",
        ptype="float_pair",
        default=[0.8, 1.25],
        label="关节刚度缩放",
        summary="PD 刚度乘随机系数。真机刚度和仿真对不上时，这项比把质量随机得更有用。",
        bigger="Transfer 已经放到 0.3–3.0，很狠。",
        smaller="更相信仿真标定。",
        novice="Hold 保持窄；进 Stage B 再加宽。",
    ),
    _p(
        id="dr_robot_damp",
        group="域随机化",
        kind="hydra",
        path="env.events.robot_joint_stiffness_and_damping.params.damping_distribution_params",
        ptype="float_pair",
        default=[0.8, 1.25],
        label="关节阻尼缩放",
        summary="PD 阻尼乘随机系数。",
        bigger="手感从「飘」到「黏」都见。",
        smaller="更单一。",
        novice="跟刚度一起改，不要只动一边。",
        advanced=True,
    ),
    _p(
        id="dr_light_intensity",
        group="域随机化",
        kind="hydra",
        path="env.events.randomize_lighting.params.intensity_range",
        ptype="float_pair",
        default=[400.0, 1400.0],
        label="光照强度",
        summary="圆顶光强度采样。状态策略几乎无感；视觉任务靠它抗曝光变化。",
        bigger="更不怕曝光，早期视觉更难。",
        smaller="画面更稳定。",
        novice="开相机再动。",
        advanced=True,
    ),
    # ----- terminations -----------------------------------------------------
    _p(
        id="term_hold_steps",
        group="终止条件",
        kind="hydra",
        path="env.terminations.success.params.hold_steps",
        ptype="int",
        default=150,
        min=10,
        max=400,
        step=10,
        label="Hold 成功：最短持续步",
        summary="一局至少走这么多步才允许判成功。3 s 局 ≈ 180 步，150 表示「撑过大半局」。",
        bigger="更难刷到成功。",
        smaller="更容易被判成功，统计会虚高。",
        novice="保持 150。",
        tasks=["PAN-CoinHold-Apex-v0", "PAN-CoinHold-Apex-Vision-v0", "PAN-CoinHold-Apex-Left-v0"],
    ),
    _p(
        id="term_stable_steps",
        group="终止条件",
        kind="hydra",
        path="env.terminations.success.params.stable_steps",
        ptype="int",
        default=30,
        min=5,
        max=180,
        step=5,
        label="Hold 成功：末段稳定步",
        summary="最后连续这么多步都在「坐稳」带内。避免「晃了一局最后一帧碰巧在座位上」。",
        bigger="更严。",
        smaller="更松。",
        novice="保持 30（约 0.5 s）。",
        tasks=["PAN-CoinHold-Apex-v0", "PAN-CoinHold-Apex-Vision-v0", "PAN-CoinHold-Apex-Left-v0"],
    ),
    _p(
        id="term_max_speed",
        group="终止条件",
        kind="hydra",
        path="env.terminations.success.params.max_speed",
        ptype="float",
        default=0.45,
        min=0.05,
        max=2.0,
        step=0.05,
        label="Hold 成功：最大线速度",
        summary="硬币比这还快就不算坐稳。",
        bigger="允许更晃。",
        smaller="必须更静止。",
        novice="保持 0.45。",
        tasks=["PAN-CoinHold-Apex-v0", "PAN-CoinHold-Apex-Vision-v0", "PAN-CoinHold-Apex-Left-v0"],
        advanced=True,
    ),
    # ----- object physics (scalar overrides after preset) -------------------
    _p(
        id="obj_radius",
        group="物体物理",
        kind="hydra",
        path="env.scene.object.spawn.radius",
        ptype="float",
        default=0.016,
        min=0.005,
        max=0.05,
        step=0.001,
        label="半径（米）",
        summary="球/硬币半径。界面里按毫米想，这里按米写（45 mm → 0.0225）。换预设会先整段替换几何，再被这项覆盖。",
        bigger="更好抓、更重（若用密度）或只是更大（若质量单独设）。",
        smaller="更难稳定。",
        novice="先换预设，再微调。硬币 0.016，45 mm 球 0.0225。",
    ),
    _p(
        id="obj_mass",
        group="物体物理",
        kind="hydra",
        path="env.scene.object.spawn.mass_props.mass",
        ptype="float",
        default=0.004,
        min=0.001,
        max=0.2,
        step=0.001,
        label="质量（千克）",
        summary="按千克。界面按克想：4 g 硬币 = 0.004。球类预设用 mass 而不是 density，所以这项能直接改重量。",
        bigger="惯性更大、更砸手、更不容易被弹飞。",
        smaller="轻飘，接触一抖就飞。",
        novice="硬币约 4 g；45 mm 保健球约 50–80 g（0.05–0.08）。",
    ),
    _p(
        id="obj_mu_s",
        group="物体物理",
        kind="hydra",
        path="env.scene.object.spawn.physics_material.static_friction",
        ptype="float",
        default=0.70,
        min=0.05,
        max=2.0,
        step=0.05,
        label="静摩擦（名义）",
        summary="生成时的名义静摩擦，域随机化会在这附近再采样。",
        bigger="更黏，更好停，更难点滚。",
        smaller="更滑。",
        novice="0.6–0.8 是塑料/漆球的合理起点。",
    ),
    _p(
        id="obj_mu_d",
        group="物体物理",
        kind="hydra",
        path="env.scene.object.spawn.physics_material.dynamic_friction",
        ptype="float",
        default=0.65,
        min=0.05,
        max=2.0,
        step=0.05,
        label="动摩擦（名义）",
        summary="滑动之后的摩擦。通常略低于静摩擦。",
        bigger="滑起来也黏。",
        smaller="一滑就停不住。",
        novice="比静摩擦低 0.05 左右。",
        advanced=True,
    ),
    _p(
        id="obj_restitution",
        group="物体物理",
        kind="hydra",
        path="env.scene.object.spawn.physics_material.restitution",
        ptype="float",
        default=0.0,
        min=0.0,
        max=0.8,
        step=0.05,
        label="弹性（恢复系数）",
        summary="0 = 完全无弹。硬币必须是 0，否则指背轻微重叠会把它弹飞。",
        bigger="更像橡皮球。",
        smaller="更像湿黏土。",
        novice="硬币保持 0；保健球可以 0.05–0.15。",
    ),
    _p(
        id="cam_width",
        group="相机",
        kind="hydra",
        path="env.scene.wrist_camera.width",
        ptype="int",
        default=128,
        min=32,
        max=256,
        step=32,
        label="相机边长（像素）",
        summary="只对 Vision 任务有效。三路 128² RGB 在 12 GB 上就要把并行环境压到 128。",
        bigger="更清晰，显存暴涨。当前策略是 MLP，像素并不会被它用上。",
        smaller="更省。64 够做预览。",
        novice="先 64 看画面，确认摆位再 128。不要开 256。",
        tasks=["PAN-CoinHold-Apex-Vision-v0"],
    ),
]


GROUPS_ORDER = [
    "规模与时长",
    "PPO",
    "网络",
    "奖励 · Hold / 共用",
    "奖励 · Transfer",
    "奖励 · 保健球",
    "域随机化",
    "终止条件",
    "物体物理",
    "相机",
]


def schema_payload() -> dict[str, Any]:
    return {
        "tasks": TASKS,
        "objects": OBJECT_PRESETS,
        "hand_poses": HAND_POSES,
        "physics": PHYSICS_BACKENDS,
        "cameras": CAMERA_LAYOUTS,
        "groups": GROUPS_ORDER,
        "params": [p.to_dict() for p in PARAMS],
        "sandbox": sandbox_schema(),
    }


def params_markdown() -> str:
    """Render the catalog as a Chinese markdown encyclopedia."""
    lines = [
        "# 训练参数百科",
        "",
        "本文由 `webui/schema.py` 生成，和界面上的 ⓘ 是同一份解释。改参数说明请改 schema，不要只改这个文件。",
        "",
    ]
    by_group: dict[str, list[Param]] = {g: [] for g in GROUPS_ORDER}
    for p in PARAMS:
        by_group.setdefault(p.group, []).append(p)
    for group in GROUPS_ORDER:
        lines.append(f"## {group}")
        lines.append("")
        for p in by_group.get(group, []):
            lines.append(f"### {p.label}")
            lines.append("")
            lines.append(f"- **路径**：`{p.path}`（{p.kind}）")
            lines.append(f"- **默认**：`{p.default}`")
            lines.append(f"- **作用**：{p.summary}")
            lines.append(f"- **调大**：{p.bigger}")
            lines.append(f"- **调小**：{p.smaller}")
            lines.append(f"- **新手**：{p.novice}")
            lines.append("")
    return "\n".join(lines)
